### ISSUE TITLE
Linux/windows compatability problems

### ISSUE THREAD

**Issue by richardbeare** [GNtem2/DENMARK-lvostroke#8]
At the moment any change made to a text file in linux causes the entire file to be different, as the end of line markers are different.

I've added a .gitattributes file, which is meant to deal with this, but I'm not sure how it will behave first time around.

**Comment by GNtem2** [comment]
Thanks. The NUTS2 file is the one used now as the smaller regions have been merged into just 5 regions. The commune data is in the europeRGDK.Rda file in github
